name: Frontend CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: lightning

      - name: Check linting
        run: bun lint
        working-directory: lightning

      - name: Run the tests
        run: bun run test
        working-directory: lightning

      - name: Build
        run: bun run build
        working-directory: lightning
